#!/usr/bin/env python3
"""Protect the static assembler's content and read-only freshness contracts."""

from __future__ import annotations

import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest.mock import patch


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "scripts"))

import build_site as builder  # noqa: E402


class BuildSiteTests(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.fixture = Path(temporary.name)
        self.root = self.fixture / "site"
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n  <!-- include: sites/hobbies/content.html -->\n</body>\n')
        self.write("sites/hobbies/content.html", '<section lang="zh-HK">香港 &amp; hobbies</section>\n')

    def write(self, name: str, content: str) -> Path:
        target = self.root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return target

    def run_main(self, *arguments: str) -> tuple[int, str, str]:
        stdout, stderr = io.StringIO(), io.StringIO()
        render = builder.render
        # render's default root is bound at definition time; supply the fixture explicitly.
        with patch.object(builder, "ROOT", self.root), patch.object(builder, "render", lambda: render(self.root)):
            with patch.object(sys, "argv", ["build_site.py", *arguments]), redirect_stdout(stdout), redirect_stderr(stderr):
                status = builder.main()
        return status, stdout.getvalue(), stderr.getvalue()

    def test_render_preserves_content_and_relative_indentation(self) -> None:
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n\t<!-- include: sites/hobbies/content.html -->\n  <!-- include: sites/portfolio/content.html -->\n</body>\n')
        self.write("sites/hobbies/content.html", '<section lang="zh-HK">\n  <p>香港 &amp; 日本語 · {{ literal }}</p>\n\n  <!-- Keep this comment. -->\n</section>\n')
        self.write("sites/portfolio/content.html", '<p id="work">Work &lt; examples</p>\n')

        self.assertEqual(
            builder.render(self.root),
            '<!DOCTYPE html>\n'
            '<!-- Generated by scripts/build_site.py; edit desktop/page.html, sites/*/content.html, or sites/projects/projects.json. -->\n'
            '<body>\n'
            '\t<section lang="zh-HK">\n'
            '\t  <p>香港 &amp; 日本語 · {{ literal }}</p>\n'
            '\n'
            '\t  <!-- Keep this comment. -->\n'
            '\t</section>\n'
            '  <p id="work">Work &lt; examples</p>\n'
            '</body>\n',
        )

    def test_malformed_or_unsupported_includes_fail(self) -> None:
        for marker in (
            "<!-- include: sites/hobbies/content.html --> trailing text",
            "<!-- include: sites/hobbies/missing.html -->",
            "<!-- include: sites/hobbies/content.html --> <!-- another marker -->",
            "<!-- include: ../outside.html -->",
            "<!-- include: sites/../outside/content.html -->",
            "<!-- include: /sites/hobbies/content.html -->",
        ):
            with self.subTest(marker=marker):
                self.write("desktop/page.html", f"<!DOCTYPE html>\n{marker}\n")
                with self.assertRaisesRegex(ValueError, "Unsupported include marker"):
                    builder.render(self.root)

    def test_nested_include_fails(self) -> None:
        self.write("sites/hobbies/content.html", '<section>\n<!-- include: sites/portfolio/content.html -->\n</section>\n')
        with self.assertRaisesRegex(ValueError, "Nested includes"):
            builder.render(self.root)

    def test_symlink_cannot_escape_sites_directory(self) -> None:
        outside = self.fixture / "outside.html"
        outside.write_text("Private content", encoding="utf-8")
        fragment = self.root / "sites/hobbies/content.html"
        fragment.unlink()
        fragment.symlink_to(outside)
        with self.assertRaisesRegex(ValueError, "Content must stay inside sites/"):
            builder.render(self.root)

    def test_missing_fragment_fails(self) -> None:
        (self.root / "sites/hobbies/content.html").unlink()
        with self.assertRaises(FileNotFoundError):
            builder.render(self.root)

    def test_check_fresh_output_succeeds_without_rewriting(self) -> None:
        target = self.write("index.html", builder.render(self.root))
        before = target.stat()
        content = target.read_bytes()
        status, stdout, stderr = self.run_main("--check")
        self.assertEqual(status, 0)
        self.assertIn("up to date", stdout)
        self.assertEqual(stderr, "")
        self.assertEqual(target.read_bytes(), content)
        self.assertEqual(target.stat().st_mtime_ns, before.st_mtime_ns)

    def test_check_stale_output_fails_without_rewriting(self) -> None:
        target = self.write("index.html", "Previously published content\n")
        before = target.stat()
        content = target.read_bytes()
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertEqual(target.read_bytes(), content)
        self.assertEqual(target.stat().st_mtime_ns, before.st_mtime_ns)

    def test_check_missing_output_fails_without_creating_it(self) -> None:
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertFalse((self.root / "index.html").exists())

    def test_build_writes_complete_rendered_page(self) -> None:
        expected = builder.render(self.root)
        self.write("index.html", "Old content")
        status, _, stderr = self.run_main()
        self.assertEqual(status, 0)
        self.assertEqual(stderr, "")
        self.assertEqual((self.root / "index.html").read_text(encoding="utf-8"), expected)

    def test_failed_build_keeps_previous_output(self) -> None:
        target = self.write("index.html", "Previously published content\n")
        (self.root / "sites/hobbies/content.html").unlink()
        status, _, stderr = self.run_main()
        self.assertEqual(status, 1)
        self.assertIn("Cannot build the site", stderr)
        self.assertEqual(target.read_text(encoding="utf-8"), "Previously published content\n")

    def add_catalogue(self) -> dict:
        data = json.loads((REPOSITORY_ROOT / "sites/projects/projects.json").read_text(encoding="utf-8"))
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n  <!-- include: sites/projects/content.html -->\n</body>\n')
        self.write("sites/projects/content.html", '<section id="project-lab">\n  <!-- project-catalogue -->\n</section>\n')
        self.write("sites/projects/projects.json", json.dumps(data))
        return data

    def test_catalogue_is_complete_static_html_with_relative_indentation(self) -> None:
        data = self.add_catalogue()
        output = builder.render(self.root)
        self.assertNotIn("<!-- project-catalogue", output)
        self.assertIn('    <details class="project-browser"', output)
        self.assertIn('id="project-lab-updates"', output)
        for project in data["projects"]:
            self.assertIn(f'id="project-lab-{project["id"]}"', output)
        self.assertEqual(output.count("data-project-panel"), len(data["projects"]))

    def test_json_change_makes_check_fail_without_rewriting(self) -> None:
        data = self.add_catalogue()
        target = self.write("index.html", builder.render(self.root))
        before = target.read_bytes()
        data["projects"][0]["currentFocus"] = "Changed focus supplied by the author."
        self.write("sites/projects/projects.json", json.dumps(data))
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertEqual(target.read_bytes(), before)

    def test_catalogue_marker_is_narrow_and_rejects_duplicates_or_malformed_markers(self) -> None:
        self.add_catalogue()
        for content in (
            "<!-- project-catalogue -->\n<!-- project-catalogue -->\n",
            "<!-- project-catalogue --> trailing text\n",
            "<!-- project-catalogue -->\n<!-- project-catalogue: other.json -->\n",
        ):
            with self.subTest(content=content):
                self.write("sites/projects/content.html", content)
                with self.assertRaisesRegex(ValueError, "project-catalogue"):
                    builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- project-catalogue -->\n')
        with self.assertRaisesRegex(ValueError, "belongs in"):
            builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- include: sites/hobbies/content.html -->\n')
        self.write("sites/hobbies/content.html", '<!-- project-catalogue -->\n')
        with self.assertRaisesRegex(ValueError, "only in"):
            builder.render(self.root)

    def test_invalid_json_preserves_last_successful_build(self) -> None:
        self.add_catalogue()
        target = self.write("index.html", builder.render(self.root))
        before = target.read_bytes()
        self.write("sites/projects/projects.json", "{")
        status, _, stderr = self.run_main()
        self.assertEqual(status, 1)
        self.assertIn("Cannot build the site", stderr)
        self.assertEqual(target.read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
