#!/usr/bin/env python3
"""Protect the static assembler's content and read-only freshness contracts."""

from __future__ import annotations

import io
import json
import sys
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "scripts"))

import build_site as builder  # noqa: E402
import site_config  # noqa: E402


class BuildSiteTests(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.fixture = Path(temporary.name)
        self.root = self.fixture / "site"
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n  <!-- include: sites/hobbies/content.html -->\n</body>\n')
        self.write("sites/hobbies/content.html", '<section lang="zh-HK">香港 &amp; hobbies</section>\n')
        self.write("desktop/styles.css", "/* Desktop fixture */\n")
        for site in ("portfolio", "hobbies", "my-websites"):
            self.write(f"sites/{site}/site.js", "export function createSite() {}\n")
            self.write(f"sites/{site}/styles.css", f"/* {site} fixture */\n")

    def write(self, name: str, content: str) -> Path:
        target = self.root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return target

    def run_main(self, *arguments: str) -> tuple[int, str, str]:
        stdout, stderr = io.StringIO(), io.StringIO()
        render = builder.render
        render_registry = builder.render_site_registry
        render_styles = builder.render_site_styles
        # The functions bind the repository root as a default; supply this fixture.
        with patch.object(builder, "ROOT", self.root), patch.object(builder, "render", lambda *_: render(self.root)), patch.object(builder, "render_site_registry", lambda *_: render_registry(self.root)), patch.object(builder, "render_site_styles", lambda *_: render_styles(self.root)):
            with patch.object(sys, "argv", ["build_site.py", *arguments]), redirect_stdout(stdout), redirect_stderr(stderr):
                status = builder.main()
        return status, stdout.getvalue(), stderr.getvalue()

    def write_outputs(self) -> dict[str, Path]:
        return {
            "index": self.write("index.html", builder.render(self.root)),
            "registry": self.write("assets/js/site-registry.js", builder.render_site_registry(self.root)),
            "styles": self.write("assets/css/one-page.css", builder.render_site_styles(self.root)),
        }

    def test_render_preserves_content_and_relative_indentation(self) -> None:
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n\t<!-- include: sites/hobbies/content.html -->\n  <!-- include: sites/portfolio/content.html -->\n</body>\n')
        self.write("sites/hobbies/content.html", '<section lang="zh-HK">\n  <p>香港 &amp; 日本語 · {{ literal }}</p>\n\n  <!-- Keep this comment. -->\n</section>\n')
        self.write("sites/portfolio/content.html", '<p id="work">Work &lt; examples</p>\n')

        self.assertEqual(
            builder.render(self.root),
            '<!DOCTYPE html>\n'
            '<!-- Generated by scripts/build_site.py; edit desktop/page.html or source files under sites/. -->\n'
            '<body>\n'
            '\t<section lang="zh-HK">\n'
            '\t  <p>香港 &amp; 日本語 · {{ literal }}</p>\n'
            '\n'
            '\t  <!-- Keep this comment. -->\n'
            '\t</section>\n'
            '  <p id="work">Work &lt; examples</p>\n'
            '</body>\n',
        )

    def test_malformed_or_unsupported_includes_fail(self) -> None:
        for marker in (
            "<!-- include: sites/hobbies/content.html --> trailing text",
            "<!-- include: sites/hobbies/missing.html -->",
            "<!-- include: sites/hobbies/content.html --> <!-- another marker -->",
            "<!-- include: ../outside.html -->",
            "<!-- include: sites/../outside/content.html -->",
            "<!-- include: /sites/hobbies/content.html -->",
        ):
            with self.subTest(marker=marker):
                self.write("desktop/page.html", f"<!DOCTYPE html>\n{marker}\n")
                with self.assertRaisesRegex(ValueError, "Unsupported include marker"):
                    builder.render(self.root)

    def test_nested_include_fails(self) -> None:
        self.write("sites/hobbies/content.html", '<section>\n<!-- include: sites/portfolio/content.html -->\n</section>\n')
        with self.assertRaisesRegex(ValueError, "Nested includes"):
            builder.render(self.root)

    def test_symlink_cannot_escape_sites_directory(self) -> None:
        outside = self.fixture / "outside.html"
        outside.write_text("Private content", encoding="utf-8")
        fragment = self.root / "sites/hobbies/content.html"
        fragment.unlink()
        fragment.symlink_to(outside)
        with self.assertRaisesRegex(ValueError, "Content must stay inside sites/"):
            builder.render(self.root)

    def test_missing_fragment_fails(self) -> None:
        (self.root / "sites/hobbies/content.html").unlink()
        with self.assertRaises(FileNotFoundError):
            builder.render(self.root)

    def test_site_without_html_gate_cannot_be_disabled_silently(self) -> None:
        sites = tuple(replace(site, enabled=False) if site.folder == "hobbies" else site for site in site_config.SITES)
        with patch.object(site_config, "SITES", sites):
            with self.assertRaisesRegex(ValueError, "no HTML feature gate"):
                builder.render(self.root)

    def test_check_fresh_output_succeeds_without_rewriting(self) -> None:
        targets = self.write_outputs()
        before = {name: (path.stat().st_mtime_ns, path.read_bytes()) for name, path in targets.items()}
        status, stdout, stderr = self.run_main("--check")
        self.assertEqual(status, 0)
        self.assertIn("up to date", stdout)
        self.assertEqual(stderr, "")
        for name, path in targets.items():
            self.assertEqual((path.stat().st_mtime_ns, path.read_bytes()), before[name])

    def test_check_stale_output_fails_without_rewriting(self) -> None:
        targets = self.write_outputs()
        target = self.write("index.html", "Previously published content\n")
        before = target.stat()
        content = target.read_bytes()
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertEqual(target.read_bytes(), content)
        self.assertEqual(target.stat().st_mtime_ns, before.st_mtime_ns)
        self.assertTrue(targets["registry"].exists())
        self.assertTrue(targets["styles"].exists())

    def test_check_detects_stale_generated_assets_without_rewriting(self) -> None:
        targets = self.write_outputs()
        for name in ("registry", "styles"):
            with self.subTest(name=name):
                target = targets[name]
                target.write_text("Stale generated asset\n", encoding="utf-8")
                before = (target.stat().st_mtime_ns, target.read_bytes())
                status, _, stderr = self.run_main("--check")
                self.assertEqual(status, 1)
                self.assertIn("out of date", stderr)
                self.assertEqual((target.stat().st_mtime_ns, target.read_bytes()), before)
                target.write_text(builder.render_site_registry(self.root) if name == "registry" else builder.render_site_styles(self.root), encoding="utf-8")

    def test_check_missing_output_fails_without_creating_it(self) -> None:
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertFalse((self.root / "index.html").exists())

    def test_build_writes_complete_rendered_page(self) -> None:
        expected = builder.render(self.root)
        expected_registry = builder.render_site_registry(self.root)
        expected_styles = builder.render_site_styles(self.root)
        self.write("index.html", "Old content")
        status, _, stderr = self.run_main()
        self.assertEqual(status, 0)
        self.assertEqual(stderr, "")
        self.assertEqual((self.root / "index.html").read_text(encoding="utf-8"), expected)
        self.assertEqual((self.root / "assets/js/site-registry.js").read_text(encoding="utf-8"), expected_registry)
        self.assertEqual((self.root / "assets/css/one-page.css").read_text(encoding="utf-8"), expected_styles)

    def test_failed_build_keeps_previous_output(self) -> None:
        target = self.write("index.html", "Previously published content\n")
        (self.root / "sites/hobbies/content.html").unlink()
        status, _, stderr = self.run_main()
        self.assertEqual(status, 1)
        self.assertIn("Cannot build the site", stderr)
        self.assertEqual(target.read_text(encoding="utf-8"), "Previously published content\n")

    def add_catalogue(self) -> dict:
        data = json.loads((REPOSITORY_ROOT / "sites/archieve/projects/projects.json").read_text(encoding="utf-8"))
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n  <!-- include: sites/projects/content.html -->\n</body>\n')
        self.write("sites/projects/content.html", '<section id="project-lab">\n  <!-- project-catalogue -->\n</section>\n')
        self.write("sites/projects/projects.json", json.dumps(data))
        return data

    def test_catalogue_is_complete_static_html_with_relative_indentation(self) -> None:
        data = self.add_catalogue()
        output = builder.render(self.root)
        self.assertNotIn("<!-- project-catalogue", output)
        self.assertIn('    <details class="project-browser"', output)
        self.assertIn('id="project-lab-updates"', output)
        for project in data["projects"]:
            self.assertIn(f'id="project-lab-{project["id"]}"', output)
        self.assertEqual(output.count("data-project-panel"), len(data["projects"]))

    def test_json_change_makes_check_fail_without_rewriting(self) -> None:
        data = self.add_catalogue()
        target = self.write_outputs()["index"]
        before = target.read_bytes()
        data["projects"][0]["currentFocus"] = "Changed focus supplied by the author."
        self.write("sites/projects/projects.json", json.dumps(data))
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertEqual(target.read_bytes(), before)

    def test_catalogue_marker_is_narrow_and_rejects_duplicates_or_malformed_markers(self) -> None:
        self.add_catalogue()
        for content in (
            "<!-- project-catalogue -->\n<!-- project-catalogue -->\n",
            "<!-- project-catalogue --> trailing text\n",
            "<!-- project-catalogue -->\n<!-- project-catalogue: other.json -->\n",
        ):
            with self.subTest(content=content):
                self.write("sites/projects/content.html", content)
                with self.assertRaisesRegex(ValueError, "project-catalogue"):
                    builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- project-catalogue -->\n')
        with self.assertRaisesRegex(ValueError, "belongs in"):
            builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- include: sites/hobbies/content.html -->\n')
        self.write("sites/hobbies/content.html", '<!-- project-catalogue -->\n')
        with self.assertRaisesRegex(ValueError, "only in"):
            builder.render(self.root)

    def test_invalid_json_preserves_last_successful_build(self) -> None:
        self.add_catalogue()
        target = self.write_outputs()["index"]
        before = target.read_bytes()
        self.write("sites/projects/projects.json", "{")
        status, _, stderr = self.run_main()
        self.assertEqual(status, 1)
        self.assertIn("Cannot build the site", stderr)
        self.assertEqual(target.read_bytes(), before)

    def add_website_shortcuts(self) -> list[dict]:
        data = [
            {"name": "Personal Hobbies", "target": "#hobby-top"},
            {"name": "DVD Project Lab", "target": "#project-lab", "feature": "project-lab"},
        ]
        self.write("desktop/page.html", '<!DOCTYPE html>\n<body>\n  <!-- include: sites/my-websites/content.html -->\n</body>\n')
        self.write("sites/my-websites/content.html", '<ul class="website-shortcut-grid">\n  <!-- website-shortcuts -->\n</ul>\n')
        self.write("sites/my-websites/websites.json", json.dumps(data))
        self.write("sites/my-websites/shortcut.html", (REPOSITORY_ROOT / "sites/my-websites/shortcut.html").read_text(encoding="utf-8"))
        return data

    def test_website_shortcuts_are_static_indented_html_and_share_lab_feature_flag(self) -> None:
        self.add_website_shortcuts()
        for enabled in (False, True):
            with self.subTest(enabled=enabled):
                output = builder.render(self.root, project_lab_enabled=enabled)
                self.assertNotIn("<!-- website-shortcuts", output)
                self.assertIn('    <li class="website-entry">\n      <a class="website-shortcut" href="#hobby-top"', output)
                self.assertEqual('href="#project-lab"' in output, enabled)

    def test_website_data_change_makes_check_fail_without_rewriting(self) -> None:
        data = self.add_website_shortcuts()
        target = self.write_outputs()["index"]
        before = target.read_bytes()
        data.append({"name": "Another Website", "target": "#another-website"})
        self.write("sites/my-websites/websites.json", json.dumps(data))
        status, _, stderr = self.run_main("--check")
        self.assertEqual(status, 1)
        self.assertIn("out of date", stderr)
        self.assertEqual(target.read_bytes(), before)

    def test_website_marker_rejects_duplicates_malformed_markers_and_wrong_locations(self) -> None:
        self.add_website_shortcuts()
        for content in (
            "<!-- website-shortcuts -->\n<!-- website-shortcuts -->\n",
            "<!-- website-shortcuts --> trailing text\n",
            "<!-- website-shortcuts -->\n<!-- website-shortcuts: other.json -->\n",
        ):
            with self.subTest(content=content):
                self.write("sites/my-websites/content.html", content)
                with self.assertRaises(ValueError):
                    builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- website-shortcuts -->\n')
        with self.assertRaises(ValueError):
            builder.render(self.root)
        self.write("desktop/page.html", '<!DOCTYPE html>\n<!-- include: sites/hobbies/content.html -->\n')
        self.write("sites/hobbies/content.html", '<!-- website-shortcuts -->\n')
        with self.assertRaises(ValueError):
            builder.render(self.root)

    def test_invalid_website_catalogue_preserves_last_successful_build(self) -> None:
        self.add_website_shortcuts()
        target = self.write_outputs()["index"]
        before = target.read_bytes()
        for source in ("{", '[{"name": "Unsafe", "target": "javascript:alert(1)"}]'):
            with self.subTest(source=source):
                self.write("sites/my-websites/websites.json", source)
                status, _, stderr = self.run_main()
                self.assertEqual(status, 1)
                self.assertIn("Cannot build the site", stderr)
                self.assertEqual(target.read_bytes(), before)


if __name__ == "__main__":
    unittest.main()
