// Generated by scripts/build_site.py; edit projects.json, excerpts.json, and locales/*.json.
export const JOURNAL_LOCALES = {
  "en": {
    "locale": "en",
    "languageName": "English",
    "ui": {
      "siteTitle": "Caleb’s Project Lab",
      "windowTitle": "Project Lab",
      "subtitle": "Personal projects and development notes",
      "home": "Home",
      "projects": "Projects",
      "updates": "Updates",
      "roadmap": "Roadmap",
      "currentWork": "Current work",
      "currentFocus": "Current focus",
      "nextStep": "Next step",
      "currentBlocker": "Current blocker",
      "links": "Links",
      "relatedProjects": "Related projects",
      "searchProjects": "Search projects",
      "searchPlaceholder": "Project name or keyword",
      "search": "Search",
      "status": "Status",
      "allStatuses": "All",
      "clearFilters": "Clear filters",
      "resultCount": "{count} projects found",
      "noResults": "No projects match your search.",
      "noResultsFor": "No projects found for “{query}”.",
      "selectedOutsideResults": "The selected project is outside the current results.",
      "noBlocker": "No blocker reported.",
      "noLinks": "No links added yet.",
      "noUpdates": "No updates added yet.",
      "noMilestones": "No milestones added yet.",
      "dateNotRecorded": "Date not recorded",
      "milestone": "Milestone",
      "personalHomepage": "Personal homepage",
      "backToPortfolio": "Back to portfolio",
      "myWebsites": "My Websites",
      "photoCredits": "Photo credits",
      "photoSource": "Source",
      "photoLicense": "License",
      "photoBy": "Photo by",
      "photoChanges": "Shinjuku and Mong Kok use unchanged source JPEGs. The Shibuya train photo has had its color and tone edited: lower brightness, slightly higher contrast, cooler tones, lower saturation, and light grain; the adapted photo remains CC BY-SA 4.0. The header displays all three with a 4:3 crop.",
      "language": "Language",
      "projectNavigation": "Project navigation",
      "sectionNavigation": "Project Lab sections",
      "projectResults": "Project search results",
      "selectedProject": "Selected project",
      "photoStrip": "Street and train photographs from Tokyo and Hong Kong",
      "skipToProjects": "Skip to projects",
      "skipToCurrentWork": "Skip to current work",
      "showDetails": "Show project details",
      "featured": "Featured"
    },
    "statuses": {
      "in-progress": "In progress",
      "planned": "Planned",
      "paused": "Paused",
      "completed": "Completed"
    },
    "photos": {
      "shinjuku-rain-2016": {
        "caption": "Shinjuku · rainy night",
        "alt": "Umbrellas and bright Japanese signs along a wet Kabukicho street at night."
      },
      "yamanote-shibuya-2008-graded": {
        "caption": "Yamanote Line · Shibuya",
        "alt": "Green-striped Yamanote Line train passing the indoor Shibuya Station platform; color-graded 2008 photograph."
      },
      "mong-kok-portland-night": {
        "caption": "Mong Kok · Portland Street",
        "alt": "Dense neon signs above Portland Street at night, with the road receding through the center of the scene."
      }
    },
    "projects": {
      "anime-mcp": {
        "title": "Anime MCP",
        "summary": "Building an MCP server for anime-character search, with a focus on retrieval quality and combining lexical and embedding scores.",
        "currentFocus": "Identify retrieval bottlenecks and select embedding models for hybrid-fusion experiments.",
        "nextStep": "Select the embedding models, run hybrid-fusion experiments, and compare the results with published findings.",
        "currentBlocker": "The retrieval bottleneck has not yet been identified. Model selection and comparative experiments are needed to investigate it.",
        "milestones": {
          "evaluation-and-lexical-foundation": {
            "title": "Develop the evaluation and lexical-retrieval foundation",
            "description": "Build the evaluation setup and lexical-retrieval baseline for comparing retrieval approaches."
          },
          "select-embedding-models": {
            "title": "Select embedding models",
            "description": "Model names and the final comparison set are pending."
          },
          "run-hybrid-fusion-experiments": {
            "title": "Run hybrid-fusion experiments",
            "description": "Evaluate retrieval performance and investigate where bottlenecks appear."
          },
          "interpret-experiment-results": {
            "title": "Compare findings with published research",
            "description": "Examine whether the findings extend to anime retrieval and document differences supported by the experiments. Results are not yet available."
          }
        },
        "updates": {
          "current-research-focus": {
            "text": "The current priority is understanding retrieval bottlenecks and preparing an embedding-model comparison with hybrid fusion. Model selection and experimental results are pending."
          }
        },
        "linkLabels": {
          "https://github.com/Caleb-Leung-Kwan-Ho/Caleb-Leung-Kwan-Ho": "Public research notes",
          "https://arxiv.org/abs/2210.11934": "Research reference: An Analysis of Fusion Functions for Hybrid Retrieval"
        }
      },
      "gba-website": {
        "title": "GBA-style personal website",
        "summary": "A nearly finished personal website with a Game Boy Advance-style experience and A/B controls, running in the browser.",
        "currentFocus": "Finish the remaining houses, correct character spawning, and improve the existing gameplay.",
        "nextStep": "Add friends' houses, fix incorrect spawn locations, and refine the current gameplay.",
        "currentBlocker": null,
        "milestones": {
          "finish-website-experience": {
            "title": "Finish the browser-based website experience",
            "description": "The existing experience is nearly complete, with a small set of additions and fixes remaining."
          },
          "add-friends-houses": {
            "title": "Add friends' houses"
          },
          "fix-spawn-locations": {
            "title": "Correct character spawn locations",
            "description": "Ensure characters do not appear at the wrong location."
          },
          "refine-current-gameplay": {
            "title": "Improve the existing gameplay"
          }
        },
        "updates": {
          "website-final-additions": {
            "text": "The website is nearly finished. Remaining work includes friends' houses, spawn-location fixes, and improvements to the current gameplay. The related browser game builds on this work."
          }
        },
        "linkLabels": {}
      },
      "browser-game": {
        "title": "Browser game",
        "summary": "A game growing out of the GBA-style website, with plans for expanded gameplay, NPC behavior, character classes, and offline play with local saves.",
        "currentFocus": "Design the first version of NPC logic. Its actions are not currently organized as a state machine.",
        "nextStep": "Continue developing the NPC logic independently before deciding on the broader implementation approach.",
        "currentBlocker": null,
        "milestones": {
          "design-npc-logic-v1": {
            "title": "Design NPC logic v1",
            "description": "Initial action logic is being designed. The current version is not a state machine."
          },
          "develop-typescript-gameplay": {
            "title": "Develop expanded gameplay in TypeScript",
            "description": "Build on the website's browser-based foundation and GBA-style controls."
          },
          "add-character-classes": {
            "title": "Add a character class system"
          },
          "enable-offline-play": {
            "title": "Enable offline play",
            "description": "The goal is a free game playable locally without a game server."
          },
          "add-save-file-import-export": {
            "title": "Add local saves and save-file import/export",
            "description": "Players should be able to keep their progress and load it again. The storage method and file format have not been selected."
          }
        },
        "updates": {
          "npc-design-underway": {
            "text": "NPC logic design has started. The first version uses actions that are not yet a state machine. Offline play, character classes, expanded gameplay, and save-file import/export remain planned work."
          }
        },
        "linkLabels": {}
      },
      "gluonagent": {
        "title": "GluonAgent",
        "summary": "An agent project paused while its complexity and research needs are reassessed.",
        "currentFocus": "Paused pending further research.",
        "nextStep": "Do further research before deciding how to resume the project.",
        "currentBlocker": "The project's complexity requires more research before development can continue.",
        "milestones": {
          "further-research": {
            "title": "Research the unresolved complexity",
            "description": "Further research is needed before the project resumes."
          }
        },
        "updates": {
          "project-paused": {
            "text": "Development is paused because the project is too complex to continue without additional research."
          }
        },
        "linkLabels": {}
      }
    }
  },
  "ja": {
    "locale": "ja",
    "languageName": "日本語",
    "ui": {
      "siteTitle": "Calebのプロジェクト研究室",
      "windowTitle": "プロジェクト研究室",
      "subtitle": "個人プロジェクトと開発の記録",
      "home": "ホーム",
      "projects": "プロジェクト",
      "updates": "開発日誌",
      "roadmap": "開発計画",
      "currentWork": "現在の取り組み",
      "currentFocus": "現在の重点",
      "nextStep": "次のステップ",
      "currentBlocker": "現在の課題",
      "links": "リンク",
      "relatedProjects": "関連プロジェクト",
      "searchProjects": "プロジェクトを検索",
      "searchPlaceholder": "プロジェクト名・キーワード",
      "search": "検索",
      "status": "進捗状況",
      "allStatuses": "すべて",
      "clearFilters": "絞り込みを解除",
      "resultCount": "{count}件のプロジェクト",
      "noResults": "条件に一致するプロジェクトはありません。",
      "noResultsFor": "「{query}」に一致するプロジェクトはありません。",
      "selectedOutsideResults": "選択中のプロジェクトは、現在の検索結果に含まれていません。",
      "noBlocker": "課題の報告はありません。",
      "noLinks": "リンクはまだありません。",
      "noUpdates": "開発日誌はまだありません。",
      "noMilestones": "開発計画はまだありません。",
      "dateNotRecorded": "日付未記録",
      "milestone": "開発項目",
      "personalHomepage": "個人ホームページ",
      "backToPortfolio": "ポートフォリオに戻る",
      "myWebsites": "制作したウェブサイト",
      "photoCredits": "写真クレジット",
      "photoSource": "出典",
      "photoLicense": "ライセンス",
      "photoBy": "撮影",
      "photoChanges": "新宿と旺角は元のJPEGを変更せずに使用しています。渋谷の列車写真は色調と明暗を編集し、明るさを下げ、コントラストを少し高め、寒色寄りにし、彩度を下げ、薄い粒子を加えています。編集後の写真にもCC BY-SA 4.0が適用されます。ヘッダーでは3枚とも4:3にトリミングして表示しています。",
      "language": "言語",
      "projectNavigation": "プロジェクト一覧",
      "sectionNavigation": "プロジェクト研究室のメニュー",
      "projectResults": "プロジェクトの検索結果",
      "selectedProject": "選択中のプロジェクト",
      "photoStrip": "東京と香港の街並み・電車の写真",
      "skipToProjects": "プロジェクト一覧へ移動",
      "skipToCurrentWork": "現在の取り組みへ移動",
      "showDetails": "プロジェクトの詳細を表示",
      "featured": "注目"
    },
    "statuses": {
      "in-progress": "進行中",
      "planned": "予定",
      "paused": "一時停止中",
      "completed": "完了"
    },
    "photos": {
      "shinjuku-rain-2016": {
        "caption": "新宿・雨の夜",
        "alt": "雨の夜の新宿・歌舞伎町。傘をさした人々が、看板の並ぶ濡れた通りを歩いている。"
      },
      "yamanote-shibuya-2008-graded": {
        "caption": "山手線・渋谷駅",
        "alt": "渋谷駅の屋内ホームを通る緑の帯の山手線。2008年の写真を色調補正したもの。"
      },
      "mong-kok-portland-night": {
        "caption": "旺角・砵蘭街",
        "alt": "香港・旺角の砵蘭街。道路が画面の中央へと続き、夜空にネオンサインが密集している。"
      }
    },
    "projects": {
      "anime-mcp": {
        "title": "Anime MCP",
        "summary": "アニメキャラクターを検索するMCPサーバーを開発中。検索品質の向上と、語彙検索・埋め込み検索のスコアを組み合わせる手法に取り組んでいます。",
        "currentFocus": "検索のボトルネックを特定し、ハイブリッド検索のスコア融合実験に使う埋め込みモデルを選定する。",
        "nextStep": "埋め込みモデルを選定してスコア融合実験を行い、既存研究の知見と結果を比較する。",
        "currentBlocker": "検索のボトルネックはまだ特定できていません。原因を調べるため、モデルの選定と比較実験が必要です。",
        "milestones": {
          "evaluation-and-lexical-foundation": {
            "title": "評価環境と語彙検索の基盤を整える",
            "description": "検索手法を比較するための評価環境と、語彙検索のベースラインを構築する。"
          },
          "select-embedding-models": {
            "title": "埋め込みモデルを選定する",
            "description": "モデル名と最終的な比較対象は未定です。"
          },
          "run-hybrid-fusion-experiments": {
            "title": "ハイブリッド検索のスコア融合実験を行う",
            "description": "検索性能を評価し、どこにボトルネックがあるかを調べる。"
          },
          "interpret-experiment-results": {
            "title": "実験結果を既存研究と比較する",
            "description": "既存研究の知見がアニメ検索にも当てはまるかを検討し、実験で確認できた違いを記録する。結果はまだ出ていません。"
          }
        },
        "updates": {
          "current-research-focus": {
            "text": "現在の優先事項は、検索のボトルネックを理解し、ハイブリッド検索のスコア融合を用いた埋め込みモデルの比較を準備することです。モデルの選定と実験結果はまだ確定していません。"
          }
        },
        "linkLabels": {
          "https://github.com/Caleb-Leung-Kwan-Ho/Caleb-Leung-Kwan-Ho": "公開リサーチノート",
          "https://arxiv.org/abs/2210.11934": "参考論文：An Analysis of Fusion Functions for Hybrid Retrieval"
        }
      },
      "gba-website": {
        "title": "GBA風の個人ウェブサイト",
        "summary": "ブラウザーで動作する、ゲームボーイアドバンス風の個人ウェブサイト。A/Bボタンで操作でき、完成間近です。",
        "currentFocus": "残りの家を追加し、キャラクターの出現位置を修正して、現在のゲームプレイを改善する。",
        "nextStep": "友人の家を追加し、誤った出現位置を修正して、現在のゲームプレイを調整する。",
        "currentBlocker": null,
        "milestones": {
          "finish-website-experience": {
            "title": "ブラウザー上のウェブサイト体験を仕上げる",
            "description": "現在の体験はほぼ完成しており、残っているのは少数の追加と修正です。"
          },
          "add-friends-houses": {
            "title": "友人の家を追加する"
          },
          "fix-spawn-locations": {
            "title": "キャラクターの出現位置を修正する",
            "description": "キャラクターが誤った場所に出現しないようにする。"
          },
          "refine-current-gameplay": {
            "title": "現在のゲームプレイを改善する"
          }
        },
        "updates": {
          "website-final-additions": {
            "text": "ウェブサイトは完成間近です。残りの作業は、友人の家の追加、出現位置の修正、現在のゲームプレイの改善です。関連するブラウザーゲームは、この取り組みを土台にしています。"
          }
        },
        "linkLabels": {}
      },
      "browser-game": {
        "title": "ブラウザーゲーム",
        "summary": "GBA風ウェブサイトを発展させたゲーム。ゲームプレイの拡張、NPCの行動、キャラクターのクラス、ローカルセーブ付きのオフラインプレイを計画しています。",
        "currentFocus": "NPCロジックの最初のバージョンを設計する。現時点では、その行動はステートマシンとして構成されていません。",
        "nextStep": "全体の実装方針を決める前に、NPCロジックの設計を単独で進める。",
        "currentBlocker": null,
        "milestones": {
          "design-npc-logic-v1": {
            "title": "NPCロジックv1を設計する",
            "description": "初期の行動ロジックを設計中です。現在のバージョンはステートマシンではありません。"
          },
          "develop-typescript-gameplay": {
            "title": "TypeScriptでゲームプレイを拡張する",
            "description": "ウェブサイトのブラウザー基盤とGBA風の操作を土台に開発する。"
          },
          "add-character-classes": {
            "title": "キャラクターのクラスシステムを追加する"
          },
          "enable-offline-play": {
            "title": "オフラインプレイに対応する",
            "description": "ゲームサーバーなしでローカルに遊べる無料ゲームを目指しています。"
          },
          "add-save-file-import-export": {
            "title": "ローカルセーブとセーブファイルの入出力を追加する",
            "description": "プレイヤーが進行状況を保存し、再び読み込めるようにする。保存方式とファイル形式は未定です。"
          }
        },
        "updates": {
          "npc-design-underway": {
            "text": "NPCロジックの設計を開始しました。最初のバージョンの行動は、まだステートマシンにはなっていません。オフラインプレイ、キャラクターのクラス、ゲームプレイの拡張、セーブファイルの入出力は今後の計画です。"
          }
        },
        "linkLabels": {}
      },
      "gluonagent": {
        "title": "GluonAgent",
        "summary": "複雑さと必要な調査内容を見直すため、開発を一時停止しているエージェントプロジェクトです。",
        "currentFocus": "追加調査のため一時停止中。",
        "nextStep": "再開の進め方を決める前に、さらに調査する。",
        "currentBlocker": "プロジェクトが複雑なため、開発を続けるには追加の調査が必要です。",
        "milestones": {
          "further-research": {
            "title": "未解決の複雑な課題を調査する",
            "description": "プロジェクトを再開する前に、さらに調査する必要があります。"
          }
        },
        "updates": {
          "project-paused": {
            "text": "追加調査なしで進めるには複雑すぎるため、開発を一時停止しています。"
          }
        },
        "linkLabels": {}
      }
    }
  },
  "zh-HK": {
    "locale": "zh-HK",
    "languageName": "繁體中文（香港）",
    "ui": {
      "siteTitle": "Caleb的項目研究室",
      "windowTitle": "項目研究室",
      "subtitle": "個人項目與開發日誌",
      "home": "主頁",
      "projects": "項目",
      "updates": "開發日誌",
      "roadmap": "開發計劃",
      "currentWork": "目前的工作",
      "currentFocus": "目前重點",
      "nextStep": "下一步",
      "currentBlocker": "目前遇到的問題",
      "links": "連結",
      "relatedProjects": "相關項目",
      "searchProjects": "搜尋項目",
      "searchPlaceholder": "項目名稱或關鍵字",
      "search": "搜尋",
      "status": "狀態",
      "allStatuses": "全部",
      "clearFilters": "清除篩選條件",
      "resultCount": "找到 {count} 個項目",
      "noResults": "沒有符合搜尋條件的項目。",
      "noResultsFor": "找不到與「{query}」相符的項目。",
      "selectedOutsideResults": "目前選取的項目不在搜尋結果之內。",
      "noBlocker": "暫未有問題報告。",
      "noLinks": "暫未加入連結。",
      "noUpdates": "暫未加入開發日誌。",
      "noMilestones": "暫未加入開發計劃。",
      "dateNotRecorded": "未有記錄日期",
      "milestone": "工作項目",
      "personalHomepage": "個人主頁",
      "backToPortfolio": "返回作品集",
      "myWebsites": "我的網站",
      "photoCredits": "相片鳴謝",
      "photoSource": "來源",
      "photoLicense": "授權條款",
      "photoBy": "攝影",
      "photoChanges": "新宿與旺角相片使用未經修改的原始JPEG。澀谷列車相片經色彩及明暗調整：降低亮度、略增對比、偏冷色調、降低飽和度，並加入輕微顆粒；修改後的相片仍採用CC BY-SA 4.0授權。頁首三張相片均以4:3裁切顯示。",
      "language": "語言",
      "projectNavigation": "項目導覽",
      "sectionNavigation": "項目研究室導覽",
      "projectResults": "項目搜尋結果",
      "selectedProject": "已選取的項目",
      "photoStrip": "東京及香港的街景與列車相片",
      "skipToProjects": "跳至項目列表",
      "skipToCurrentWork": "跳至目前的工作",
      "showDetails": "查看項目詳情",
      "featured": "精選"
    },
    "statuses": {
      "in-progress": "進行中",
      "planned": "計劃中",
      "paused": "已暫停",
      "completed": "已完成"
    },
    "photos": {
      "shinjuku-rain-2016": {
        "caption": "新宿・雨夜",
        "alt": "新宿歌舞伎町雨夜，行人撐着雨傘走在濕潤的街道上，兩旁亮起密集的日文招牌。"
      },
      "yamanote-shibuya-2008-graded": {
        "caption": "山手線・澀谷站",
        "alt": "一列帶綠色橫紋的山手線列車駛經澀谷站室內月台；2008年相片經色調處理。"
      },
      "mong-kok-portland-night": {
        "caption": "旺角・砵蘭街",
        "alt": "旺角砵蘭街夜景，霓虹招牌密佈，街道由畫面中央向遠處延伸。"
      }
    },
    "projects": {
      "anime-mcp": {
        "title": "Anime MCP",
        "summary": "正在開發搜尋動畫角色的MCP伺服器，重點是改善檢索質素，以及結合詞彙檢索與嵌入模型的評分。",
        "currentFocus": "找出檢索瓶頸，並選擇用於混合檢索評分融合實驗的嵌入模型。",
        "nextStep": "選擇嵌入模型、進行混合檢索評分融合實驗，並將結果與已發表的研究比較。",
        "currentBlocker": "尚未找出檢索瓶頸，需要先選擇模型並進行比較實驗，以查明原因。",
        "milestones": {
          "evaluation-and-lexical-foundation": {
            "title": "建立評估環境與詞彙檢索基礎",
            "description": "建立評估環境和詞彙檢索基準，以比較不同的檢索方法。"
          },
          "select-embedding-models": {
            "title": "選擇嵌入模型",
            "description": "模型名稱及最終比較名單尚未確定。"
          },
          "run-hybrid-fusion-experiments": {
            "title": "進行混合檢索評分融合實驗",
            "description": "評估檢索表現，並找出瓶頸出現的位置。"
          },
          "interpret-experiment-results": {
            "title": "將實驗結果與已發表研究比較",
            "description": "研究既有發現是否同樣適用於動畫檢索，並記錄有實驗支持的差異。目前尚未有結果。"
          }
        },
        "updates": {
          "current-research-focus": {
            "text": "目前首要工作是了解檢索瓶頸，並準備以混合檢索評分融合方式比較嵌入模型。模型選擇及實驗結果仍未確定。"
          }
        },
        "linkLabels": {
          "https://github.com/Caleb-Leung-Kwan-Ho/Caleb-Leung-Kwan-Ho": "公開研究筆記",
          "https://arxiv.org/abs/2210.11934": "參考論文：An Analysis of Fusion Functions for Hybrid Retrieval"
        }
      },
      "gba-website": {
        "title": "GBA風格個人網站",
        "summary": "一個接近完成、在瀏覽器運行的個人網站，採用Game Boy Advance風格，並提供A/B按鈕操作。",
        "currentFocus": "完成餘下的房屋、修正角色生成位置，並改善現有遊戲體驗。",
        "nextStep": "加入朋友的房屋、修正錯誤的生成位置，並調整現有遊戲體驗。",
        "currentBlocker": null,
        "milestones": {
          "finish-website-experience": {
            "title": "完成瀏覽器內的網站體驗",
            "description": "現有體驗已接近完成，只剩下少量新增內容和修正。"
          },
          "add-friends-houses": {
            "title": "加入朋友的房屋"
          },
          "fix-spawn-locations": {
            "title": "修正角色生成位置",
            "description": "確保角色不會在錯誤的位置出現。"
          },
          "refine-current-gameplay": {
            "title": "改善現有遊戲體驗"
          }
        },
        "updates": {
          "website-final-additions": {
            "text": "網站已接近完成。餘下工作包括加入朋友的房屋、修正角色生成位置，以及改善現有遊戲體驗。相關的瀏覽器遊戲會以這些工作為基礎繼續開發。"
          }
        },
        "linkLabels": {}
      },
      "browser-game": {
        "title": "瀏覽器遊戲",
        "summary": "由GBA風格網站延伸的遊戲，計劃擴展玩法、NPC行為、角色職業，以及支援本機存檔的離線遊玩功能。",
        "currentFocus": "設計第一版NPC邏輯。目前的動作邏輯尚未以狀態機方式組織。",
        "nextStep": "先獨立推進NPC邏輯的設計，再決定整體實作方向。",
        "currentBlocker": null,
        "milestones": {
          "design-npc-logic-v1": {
            "title": "設計NPC邏輯v1",
            "description": "正在設計初步的動作邏輯。目前版本並非狀態機。"
          },
          "develop-typescript-gameplay": {
            "title": "以TypeScript擴展遊戲玩法",
            "description": "以網站的瀏覽器基礎及GBA風格操作為基礎繼續開發。"
          },
          "add-character-classes": {
            "title": "加入角色職業系統"
          },
          "enable-offline-play": {
            "title": "支援離線遊玩",
            "description": "目標是製作可在本機遊玩、毋須遊戲伺服器的免費遊戲。"
          },
          "add-save-file-import-export": {
            "title": "加入本機存檔及存檔匯入／匯出功能",
            "description": "讓玩家保留遊戲進度並再次載入。儲存方式及檔案格式尚未決定。"
          }
        },
        "updates": {
          "npc-design-underway": {
            "text": "NPC邏輯設計已開始。第一版採用的動作邏輯尚未構成狀態機。離線遊玩、角色職業、擴展玩法，以及存檔匯入／匯出仍屬計劃中的工作。"
          }
        },
        "linkLabels": {}
      },
      "gluonagent": {
        "title": "GluonAgent",
        "summary": "一個已暫停開發的智能代理項目，目前正重新評估其複雜程度及研究需要。",
        "currentFocus": "已暫停，等待進一步研究。",
        "nextStep": "先進行更多研究，再決定如何恢復開發。",
        "currentBlocker": "項目的複雜程度較高，需要進一步研究才能繼續開發。",
        "milestones": {
          "further-research": {
            "title": "研究尚未解決的複雜問題",
            "description": "項目恢復開發前，需要進行更多研究。"
          }
        },
        "updates": {
          "project-paused": {
            "text": "項目過於複雜，未經進一步研究難以繼續，因此已暫停開發。"
          }
        },
        "linkLabels": {}
      }
    }
  }
};

export const JOURNAL_PROJECTS = [
  {
    "id": "anime-mcp",
    "title": "Anime MCP",
    "status": "in-progress",
    "featured": true,
    "summary": "Building an MCP server for anime-character search, with a focus on retrieval quality and combining lexical and embedding scores.",
    "currentFocus": "Identify retrieval bottlenecks and select embedding models for hybrid-fusion experiments.",
    "nextStep": "Select the embedding models, run hybrid-fusion experiments, and compare the results with published findings.",
    "currentBlocker": "The retrieval bottleneck has not yet been identified. Model selection and comparative experiments are needed to investigate it.",
    "relatedProjectIds": [],
    "milestones": [
      {
        "id": "evaluation-and-lexical-foundation",
        "title": "Develop the evaluation and lexical-retrieval foundation",
        "status": "in-progress",
        "description": "Build the evaluation setup and lexical-retrieval baseline for comparing retrieval approaches."
      },
      {
        "id": "select-embedding-models",
        "title": "Select embedding models",
        "status": "planned",
        "description": "Model names and the final comparison set are pending."
      },
      {
        "id": "run-hybrid-fusion-experiments",
        "title": "Run hybrid-fusion experiments",
        "status": "planned",
        "description": "Evaluate retrieval performance and investigate where bottlenecks appear."
      },
      {
        "id": "interpret-experiment-results",
        "title": "Compare findings with published research",
        "status": "planned",
        "description": "Examine whether the findings extend to anime retrieval and document differences supported by the experiments. Results are not yet available."
      }
    ],
    "updates": [
      {
        "id": "current-research-focus",
        "date": null,
        "text": "The current priority is understanding retrieval bottlenecks and preparing an embedding-model comparison with hybrid fusion. Model selection and experimental results are pending."
      }
    ],
    "links": [
      {
        "label": "Public research notes",
        "url": "https://github.com/Caleb-Leung-Kwan-Ho/Caleb-Leung-Kwan-Ho"
      },
      {
        "label": "Research reference: An Analysis of Fusion Functions for Hybrid Retrieval",
        "url": "https://arxiv.org/abs/2210.11934"
      }
    ]
  },
  {
    "id": "gba-website",
    "title": "GBA-style personal website",
    "status": "in-progress",
    "featured": false,
    "summary": "A nearly finished personal website with a Game Boy Advance-style experience and A/B controls, running in the browser.",
    "currentFocus": "Finish the remaining houses, correct character spawning, and improve the existing gameplay.",
    "nextStep": "Add friends' houses, fix incorrect spawn locations, and refine the current gameplay.",
    "currentBlocker": null,
    "relatedProjectIds": [
      "browser-game"
    ],
    "milestones": [
      {
        "id": "finish-website-experience",
        "title": "Finish the browser-based website experience",
        "status": "in-progress",
        "description": "The existing experience is nearly complete, with a small set of additions and fixes remaining."
      },
      {
        "id": "add-friends-houses",
        "title": "Add friends' houses",
        "status": "planned"
      },
      {
        "id": "fix-spawn-locations",
        "title": "Correct character spawn locations",
        "status": "planned",
        "description": "Ensure characters do not appear at the wrong location."
      },
      {
        "id": "refine-current-gameplay",
        "title": "Improve the existing gameplay",
        "status": "planned"
      }
    ],
    "updates": [
      {
        "id": "website-final-additions",
        "date": null,
        "text": "The website is nearly finished. Remaining work includes friends' houses, spawn-location fixes, and improvements to the current gameplay. The related browser game builds on this work."
      }
    ],
    "links": []
  },
  {
    "id": "browser-game",
    "title": "Browser game",
    "status": "in-progress",
    "featured": false,
    "summary": "A game growing out of the GBA-style website, with plans for expanded gameplay, NPC behavior, character classes, and offline play with local saves.",
    "currentFocus": "Design the first version of NPC logic. Its actions are not currently organized as a state machine.",
    "nextStep": "Continue developing the NPC logic independently before deciding on the broader implementation approach.",
    "currentBlocker": null,
    "relatedProjectIds": [
      "gba-website"
    ],
    "milestones": [
      {
        "id": "design-npc-logic-v1",
        "title": "Design NPC logic v1",
        "status": "in-progress",
        "description": "Initial action logic is being designed. The current version is not a state machine."
      },
      {
        "id": "develop-typescript-gameplay",
        "title": "Develop expanded gameplay in TypeScript",
        "status": "planned",
        "description": "Build on the website's browser-based foundation and GBA-style controls."
      },
      {
        "id": "add-character-classes",
        "title": "Add a character class system",
        "status": "planned"
      },
      {
        "id": "enable-offline-play",
        "title": "Enable offline play",
        "status": "planned",
        "description": "The goal is a free game playable locally without a game server."
      },
      {
        "id": "add-save-file-import-export",
        "title": "Add local saves and save-file import/export",
        "status": "planned",
        "description": "Players should be able to keep their progress and load it again. The storage method and file format have not been selected."
      }
    ],
    "updates": [
      {
        "id": "npc-design-underway",
        "date": null,
        "text": "NPC logic design has started. The first version uses actions that are not yet a state machine. Offline play, character classes, expanded gameplay, and save-file import/export remain planned work."
      }
    ],
    "links": []
  },
  {
    "id": "gluonagent",
    "title": "GluonAgent",
    "status": "paused",
    "featured": false,
    "summary": "An agent project paused while its complexity and research needs are reassessed.",
    "currentFocus": "Paused pending further research.",
    "nextStep": "Do further research before deciding how to resume the project.",
    "currentBlocker": "The project's complexity requires more research before development can continue.",
    "relatedProjectIds": [],
    "milestones": [
      {
        "id": "further-research",
        "title": "Research the unresolved complexity",
        "status": "planned",
        "description": "Further research is needed before the project resumes."
      }
    ],
    "updates": [
      {
        "id": "project-paused",
        "date": null,
        "text": "Development is paused because the project is too complex to continue without additional research."
      }
    ],
    "links": []
  }
];

export const JOURNAL_EXCERPTS = {
  "en": {
    "anime-mcp": {
      "summary": "Developing an anime-character search MCP server with hybrid retrieval.",
      "currentFocus": "Find retrieval bottlenecks and choose embedding models.",
      "nextStep": "Run hybrid-fusion experiments and compare findings with published research.",
      "updates": {
        "current-research-focus": "Preparing a model comparison; selection and results are pending."
      }
    },
    "gba-website": {
      "summary": "A nearly finished GBA-style browser website with A/B controls.",
      "currentFocus": "Finish houses, spawning fixes, and gameplay refinements.",
      "nextStep": "Add friends' houses and correct spawn locations.",
      "updates": {
        "website-final-additions": "Final additions: friends' houses, spawning fixes, and gameplay."
      }
    },
    "browser-game": {
      "summary": "A browser game growing out of the GBA-style website.",
      "currentFocus": "Design NPC logic v1; it is not yet a state machine.",
      "nextStep": "Develop NPC logic before choosing the broader implementation approach.",
      "updates": {
        "npc-design-underway": "NPC logic underway; expanded gameplay, classes, offline play, and saves planned."
      }
    },
    "gluonagent": {
      "summary": "An agent project paused for more research.",
      "currentFocus": "Reassess the project's complexity and research needs.",
      "nextStep": "Research further before deciding how to resume.",
      "updates": {
        "project-paused": "Development paused: further research needed."
      }
    }
  },
  "ja": {
    "anime-mcp": {
      "summary": "ハイブリッド検索でアニメキャラクターを探すMCPサーバーを開発中。",
      "currentFocus": "検索のボトルネックを特定し、埋め込みモデルを選定する。",
      "nextStep": "スコア融合実験を行い、結果を既存研究と比較する。",
      "updates": {
        "current-research-focus": "モデル比較を準備中。モデルの選定と結果は未確定。"
      }
    },
    "gba-website": {
      "summary": "A/Bボタンで操作するGBA風の個人ウェブサイト。完成間近です。",
      "currentFocus": "家の追加、出現位置の修正、ゲームプレイの改善。",
      "nextStep": "友人の家を追加し、誤った出現位置を修正する。",
      "updates": {
        "website-final-additions": "完成に向けて、友人の家・出現位置・ゲームプレイを調整。"
      }
    },
    "browser-game": {
      "summary": "GBA風ウェブサイトを発展させたブラウザーゲーム。",
      "currentFocus": "NPCロジックv1を設計中。まだステートマシンではありません。",
      "nextStep": "全体の実装方針を決める前に、NPCロジックの設計を進める。",
      "updates": {
        "npc-design-underway": "NPCロジックを設計中。ゲーム拡張・クラス・オフライン・セーブは計画段階。"
      }
    },
    "gluonagent": {
      "summary": "追加調査のため、開発を一時停止したエージェントプロジェクト。",
      "currentFocus": "プロジェクトの複雑さと調査の必要性を見直す。",
      "nextStep": "再開方法を決める前に、さらに調査する。",
      "updates": {
        "project-paused": "追加調査が必要なため、開発を一時停止中。"
      }
    }
  },
  "zh-HK": {
    "anime-mcp": {
      "summary": "正在開發以混合檢索搜尋動畫角色的MCP伺服器。",
      "currentFocus": "找出檢索瓶頸，並選擇嵌入模型。",
      "nextStep": "進行評分融合實驗，並與已發表的研究比較結果。",
      "updates": {
        "current-research-focus": "準備模型比較；模型選擇及結果仍未確定。"
      }
    },
    "gba-website": {
      "summary": "接近完成的GBA風格瀏覽器個人網站，提供A/B按鈕操作。",
      "currentFocus": "完成房屋、修正生成位置，並改善遊戲體驗。",
      "nextStep": "加入朋友的房屋，並修正錯誤的生成位置。",
      "updates": {
        "website-final-additions": "最後新增與修正：朋友的房屋、生成位置及遊戲體驗。"
      }
    },
    "browser-game": {
      "summary": "由GBA風格網站延伸的瀏覽器遊戲。",
      "currentFocus": "正在設計NPC邏輯v1；目前並非狀態機。",
      "nextStep": "先推進NPC邏輯設計，再決定整體實作方向。",
      "updates": {
        "npc-design-underway": "NPC邏輯設計中；擴展玩法、職業、離線遊玩及存檔仍屬計劃。"
      }
    },
    "gluonagent": {
      "summary": "為進一步研究而暫停開發的智能代理項目。",
      "currentFocus": "重新評估項目的複雜程度及研究需要。",
      "nextStep": "先進行更多研究，再決定如何恢復開發。",
      "updates": {
        "project-paused": "需要進一步研究，開發已暫停。"
      }
    }
  }
};
