#!/usr/bin/env python3
"""Assemble the desktop template and local content into the published index.html."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
INCLUDE = re.compile(r"^([\t ]*)<!-- include: (sites/[a-z0-9-]+/content\.html) -->$", re.MULTILINE)
NOTICE = "<!-- Generated by scripts/build_site.py; edit desktop/page.html or sites/*/content.html. -->\n"


def render(root: Path = ROOT) -> str:
    """Only local content fragments are included; there is no template execution."""
    template = (root / "desktop/page.html").read_text(encoding="utf-8")

    def include(match: re.Match[str]) -> str:
        indent, name = match.groups()
        source = (root / name).resolve()
        if not source.is_relative_to((root / "sites").resolve()):
            raise ValueError(f"Content must stay inside sites/: {name}")
        content = source.read_text(encoding="utf-8").rstrip("\n")
        if "<!-- include:" in content:
            raise ValueError(f"Nested includes are not supported: {name}")
        return "\n".join(indent + line if line else line for line in content.split("\n"))

    output = INCLUDE.sub(include, template)
    if "<!-- include:" in output:
        raise ValueError("Unsupported include marker in desktop/page.html")
    first_line, remainder = output.split("\n", 1)
    return first_line + "\n" + NOTICE + remainder


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale output without changing files.")
    args = parser.parse_args()
    try:
        output = render()
        target = ROOT / "index.html"
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != output:
                print("index.html is out of date. Run python3 scripts/build_site.py.", file=sys.stderr)
                return 1
            print("Generated HTML is up to date.")
        else:
            target.write_text(output, encoding="utf-8")
            print("Built index.html from desktop/page.html and site content.")
    except (OSError, ValueError) as error:
        print(f"Cannot build the site: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
