#!/usr/bin/env python3
"""Assemble the desktop template and local content into the published index.html."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

from project_content import render_catalogue


ROOT = Path(__file__).resolve().parents[1]
# Set to True, then run python3 scripts/build_site.py to re-enable DVD Project Lab.
PROJECT_LAB_ENABLED = False
PROJECT_LAB_BLOCK = re.compile(r"^[\t ]*<!-- project-lab:start -->\n(.*?)^[\t ]*<!-- project-lab:end -->[\t ]*(?:\n|$)", re.MULTILINE | re.DOTALL)
INCLUDE = re.compile(r"^([\t ]*)<!-- include: (sites/[a-z0-9-]+/content\.html) -->$", re.MULTILINE)
CATALOGUE = re.compile(r"^([\t ]*)<!-- project-catalogue -->$", re.MULTILINE)
NOTICE = "<!-- Generated by scripts/build_site.py; edit desktop/page.html, sites/*/content.html, or sites/projects/projects.json. -->\n"


def project_lab_content(source: str, enabled: bool) -> str:
    """Omit the dormant lab before loading its includes or catalogue."""
    def replace(match: re.Match[str]) -> str:
        content = match[1]
        if "<!-- project-lab:" in content:
            raise ValueError("Nested Project Lab feature blocks are not supported")
        return content if enabled else ""

    output = PROJECT_LAB_BLOCK.sub(replace, source)
    if "<!-- project-lab:" in output:
        raise ValueError("Unsupported or unmatched Project Lab feature marker")
    return output


def render(root: Path = ROOT, *, project_lab_enabled: bool | None = None) -> str:
    """Include local fragments and validated project data without template execution."""
    enabled = PROJECT_LAB_ENABLED if project_lab_enabled is None else project_lab_enabled
    template = project_lab_content((root / "desktop/page.html").read_text(encoding="utf-8"), enabled)

    def include(match: re.Match[str]) -> str:
        indent, name = match.groups()
        source = (root / name).resolve()
        if not source.is_relative_to((root / "sites").resolve()):
            raise ValueError(f"Content must stay inside sites/: {name}")
        content = project_lab_content(source.read_text(encoding="utf-8"), enabled).rstrip("\n")
        if "<!-- include:" in content:
            raise ValueError(f"Nested includes are not supported: {name}")
        if "<!-- project-catalogue" in content:
            if name != "sites/projects/content.html" or len(CATALOGUE.findall(content)) != 1:
                raise ValueError("One project-catalogue marker is supported only in sites/projects/content.html")
            catalogue = render_catalogue(root)
            content = CATALOGUE.sub(lambda marker: "\n".join(marker[1] + line if line else line for line in catalogue.split("\n")), content)
            if "<!-- project-catalogue" in content:
                raise ValueError("Unsupported project-catalogue marker")
        return "\n".join(indent + line if line else line for line in content.split("\n"))

    output = INCLUDE.sub(include, template)
    if "<!-- include:" in output:
        raise ValueError("Unsupported include marker in desktop/page.html")
    if "<!-- project-catalogue" in output:
        raise ValueError("Project catalogue marker belongs in sites/projects/content.html")
    first_line, remainder = output.split("\n", 1)
    return first_line + "\n" + NOTICE + remainder


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale output without changing files.")
    args = parser.parse_args()
    try:
        output = render()
        target = ROOT / "index.html"
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != output:
                print("index.html is out of date. Run python3 scripts/build_site.py.", file=sys.stderr)
                return 1
            print("Generated HTML is up to date.")
        else:
            target.write_text(output, encoding="utf-8")
            print("Built index.html from desktop/page.html and site content.")
    except (OSError, ValueError) as error:
        print(f"Cannot build the site: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
