#!/usr/bin/env python3
"""Assemble the desktop template and local content into the published index.html."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

from browser_content import render_browser_windows
from project_content import render_catalogue
from project_journal_content import render_journal, render_translations
from site_config import Site, active_sites
from website_content import render_shortcuts


ROOT = Path(__file__).resolve().parents[1]
PROJECT_LAB_BLOCK = re.compile(r"^[\t ]*<!-- project-lab:start -->\n(.*?)^[\t ]*<!-- project-lab:end -->[\t ]*(?:\n|$)", re.MULTILINE | re.DOTALL)
INCLUDE = re.compile(r"^([\t ]*)<!-- include: (sites/[a-z0-9-]+/content\.html) -->$", re.MULTILINE)
CATALOGUE = re.compile(r"^([\t ]*)<!-- project-catalogue -->$", re.MULTILINE)
WEBSITE_SHORTCUTS = re.compile(r"^([\t ]*)<!-- website-shortcuts -->$", re.MULTILINE)
JOURNAL_CONTENT = re.compile(r"^([\t ]*)<!-- project-journal-content -->$", re.MULTILINE)
NOTICE = "<!-- Generated by scripts/build_site.py; edit desktop/page.html or source files under sites/. -->\n"


def project_lab_content(source: str, enabled: bool) -> str:
    """Omit the dormant lab before loading its includes or catalogue."""
    def replace(match: re.Match[str]) -> str:
        content = match[1]
        if "<!-- project-lab:" in content:
            raise ValueError("Nested Project Lab feature blocks are not supported")
        return content if enabled else ""

    output = PROJECT_LAB_BLOCK.sub(replace, source)
    if "<!-- project-lab:" in output:
        raise ValueError("Unsupported or unmatched Project Lab feature marker")
    return output


def configured_sites(project_lab_enabled: bool | None) -> tuple[Site, ...]:
    overrides = {"projects": project_lab_enabled} if project_lab_enabled is not None else None
    return active_sites(overrides)


def render(root: Path = ROOT, *, project_lab_enabled: bool | None = None) -> str:
    """Include local fragments and validated project data without template execution."""
    sites = configured_sites(project_lab_enabled)
    enabled = any(site.feature_gate == "project-lab" for site in sites)
    template = project_lab_content((root / "desktop/page.html").read_text(encoding="utf-8"), enabled)
    template = render_browser_windows(template, root, sites)

    def include(match: re.Match[str]) -> str:
        indent, name = match.groups()
        source = (root / name).resolve()
        if not source.is_relative_to((root / "sites").resolve()):
            raise ValueError(f"Content must stay inside sites/: {name}")
        content = project_lab_content(source.read_text(encoding="utf-8"), enabled).rstrip("\n")
        if "<!-- include:" in content:
            raise ValueError(f"Nested includes are not supported: {name}")
        if "<!-- website-shortcuts" in content:
            if name != "sites/my-websites/content.html" or len(WEBSITE_SHORTCUTS.findall(content)) != 1:
                raise ValueError("One website-shortcuts marker is supported only in sites/my-websites/content.html")
            shortcuts = render_shortcuts(root, enabled_features=frozenset(site.feature_gate for site in sites if site.feature_gate))
            content = WEBSITE_SHORTCUTS.sub(lambda marker: "\n".join(marker[1] + line if line else line for line in shortcuts.split("\n")), content)
            if "<!-- website-shortcuts" in content:
                raise ValueError("Unsupported website-shortcuts marker")
        if "<!-- project-catalogue" in content:
            if name != "sites/projects/content.html" or len(CATALOGUE.findall(content)) != 1:
                raise ValueError("One project-catalogue marker is supported only in sites/projects/content.html")
            catalogue = render_catalogue(root)
            content = CATALOGUE.sub(lambda marker: "\n".join(marker[1] + line if line else line for line in catalogue.split("\n")), content)
            if "<!-- project-catalogue" in content:
                raise ValueError("Unsupported project-catalogue marker")
        if "<!-- project-journal-content" in content:
            if name != "sites/project-journal/content.html" or len(JOURNAL_CONTENT.findall(content)) != 1:
                raise ValueError("One project-journal-content marker is supported only in sites/project-journal/content.html")
            journal = render_journal(root)
            content = JOURNAL_CONTENT.sub(lambda marker: "\n".join(marker[1] + line if line else line for line in journal.split("\n")), content)
            if "<!-- project-journal-content" in content:
                raise ValueError("Unsupported project-journal-content marker")
        return "\n".join(indent + line if line else line for line in content.split("\n"))

    output = INCLUDE.sub(include, template)
    if "<!-- browser-window" in output:
        raise ValueError("Browser window markers belong in desktop/page.html")
    if "<!-- include:" in output:
        raise ValueError("Unsupported include marker in desktop/page.html")
    if "<!-- project-catalogue" in output:
        raise ValueError("Project catalogue marker belongs in sites/projects/content.html")
    if "<!-- website-shortcuts" in output:
        raise ValueError("Website shortcuts marker belongs in sites/my-websites/content.html")
    if "<!-- project-journal-content" in output:
        raise ValueError("Journal content marker belongs in sites/project-journal/content.html")
    first_line, remainder = output.split("\n", 1)
    return first_line + "\n" + NOTICE + remainder


def render_site_registry(root: Path = ROOT, *, project_lab_enabled: bool | None = None) -> str:
    """Write only active site factories as supported static imports."""
    sites = configured_sites(project_lab_enabled)
    lines = ["// Generated by scripts/build_site.py from scripts/site_config.py."]
    for site in sites:
        path = root / "sites" / site.folder / "site.js"
        if not path.is_file():
            raise FileNotFoundError(f"Active site module is missing: {path}")
        lines.append(f"import {{ {site.factory} }} from '../../sites/{site.folder}/site.js';")
    lines += ["", "export function createSites() {",
              "\treturn [" + ", ".join(f"{site.factory}()" for site in sites) + "].filter(Boolean);",
              "}"]
    return "\n".join(lines) + "\n"


def render_site_styles(root: Path = ROOT, *, project_lab_enabled: bool | None = None) -> str:
    """Preserve desktop-first CSS order for active sites only."""
    lines = ["/* Generated by scripts/build_site.py from scripts/site_config.py. */",
             '@import url("../../desktop/styles.css");']
    for site in configured_sites(project_lab_enabled):
        path = root / "sites" / site.folder / "styles.css"
        if not path.is_file():
            raise FileNotFoundError(f"Active site stylesheet is missing: {path}")
        lines.append(f'@import url("../../sites/{site.folder}/styles.css");')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale output without changing files.")
    args = parser.parse_args()
    try:
        outputs = {
            ROOT / "index.html": render(ROOT),
            ROOT / "assets/js/site-registry.js": render_site_registry(ROOT),
            ROOT / "assets/css/one-page.css": render_site_styles(ROOT),
        }
        if any(site.folder == "project-journal" for site in configured_sites(None)):
            outputs[ROOT / "sites/project-journal/translations.js"] = render_translations(ROOT)
        if args.check:
            stale = [path.relative_to(ROOT) for path, output in outputs.items()
                     if not path.exists() or path.read_text(encoding="utf-8") != output]
            if stale:
                print(f"Generated site files are out of date: {', '.join(map(str, stale))}. Run python3 scripts/build_site.py.", file=sys.stderr)
                return 1
            print("Generated site files are up to date.")
        else:
            for path, output in outputs.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(output, encoding="utf-8")
            print("Built index.html and active site JavaScript/CSS from source files.")
    except (OSError, ValueError) as error:
        print(f"Cannot build the site: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
